from typing import Any

def _col_letter(col_idx: int) -> str: ...

class Cell:
    TYPE_STRING: str
    TYPE_FORMULA: str
    TYPE_NUMERIC: str
    TYPE_BOOL: str
    TYPE_NULL: str
    TYPE_INLINE: str
    TYPE_ERROR: str
    TYPE_FORMULA_CACHE_STRING: str

    def __init__(
        self,
        row: int = 1,
        column: int = 1,
        value: Any = None,
        worksheet: Any | None = None,
    ) -> None: ...
    @property
    def row(self) -> int: ...
    @row.setter
    def row(self, val: int) -> None: ...
    @property
    def column(self) -> int: ...
    @column.setter
    def column(self, val: int) -> None: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, val: Any) -> None: ...
    @property
    def coordinate(self) -> str: ...
    @property
    def data_type(self) -> str: ...
    @property
    def font(self) -> Any | None: ...
    @font.setter
    def font(self, val: Any) -> None: ...
    @property
    def number_format(self) -> str: ...
    @number_format.setter
    def number_format(self, val: str) -> None: ...
    @property
    def alignment(self) -> Any | None: ...
    @alignment.setter
    def alignment(self, val: Any) -> None: ...
    @property
    def border(self) -> Any | None: ...
    @border.setter
    def border(self, val: Any) -> None: ...
    @property
    def fill(self) -> Any | None: ...
    @fill.setter
    def fill(self, val: Any) -> None: ...
    @property
    def hyperlink(self) -> str | None: ...
    @hyperlink.setter
    def hyperlink(self, val: Any) -> None: ...
    @property
    def comment(self) -> Any | None: ...
    @comment.setter
    def comment(self, val: Any) -> None: ...
    @property
    def protection(self) -> Any | None: ...
    @protection.setter
    def protection(self, val: Any) -> None: ...
