from collections.abc import Generator, Iterable
from typing import Any, Optional, overload

from openpyxl_rust.cell import Cell
from openpyxl_rust.page import PageMargins, PrintOptions, PrintPageSetup
from openpyxl_rust.protection import SheetProtection

class ColumnDimension:
    width: Optional[float]
    def __init__(self) -> None: ...

class RowDimension:
    height: Optional[float]
    def __init__(self) -> None: ...

class _ColumnDimensionsDict:
    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> ColumnDimension: ...
    def items(self) -> Iterable[tuple[str, ColumnDimension]]: ...

class _RowDimensionsDict:
    def __init__(self) -> None: ...
    def __getitem__(self, key: int) -> RowDimension: ...
    def items(self) -> Iterable[tuple[int, RowDimension]]: ...

class _AutoFilter:
    def __init__(self) -> None: ...
    @property
    def ref(self) -> Optional[str]: ...
    @ref.setter
    def ref(self, value: Optional[str]) -> None: ...

class _ConditionalFormattingList:
    def __init__(self) -> None: ...
    def add(self, range_string: str, rule: Any) -> None: ...

class Worksheet:
    # Class constants
    ORIENTATION_PORTRAIT: str
    ORIENTATION_LANDSCAPE: str
    PAPERSIZE_LETTER: int
    PAPERSIZE_LEGAL: int
    PAPERSIZE_A4: int
    PAPERSIZE_A5: int

    # Instance attributes
    column_dimensions: _ColumnDimensionsDict
    row_dimensions: _RowDimensionsDict
    freeze_panes: Optional[str]
    merged_cell_ranges: list[tuple[str, str]]
    auto_filter: _AutoFilter
    protection: SheetProtection
    page_setup: PrintPageSetup
    page_margins: PageMargins
    print_options: PrintOptions
    print_area: Optional[str]
    print_title_rows: Optional[str]
    print_title_cols: Optional[str]
    conditional_formatting: _ConditionalFormattingList

    def __init__(
        self,
        title: str = "Sheet",
        workbook: Optional[Any] = None,
        sheet_idx: Optional[int] = None,
    ) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def min_row(self) -> Optional[int]: ...
    @property
    def max_row(self) -> Optional[int]: ...
    @property
    def min_column(self) -> Optional[int]: ...
    @property
    def max_column(self) -> Optional[int]: ...
    @property
    def dimensions(self) -> str: ...
    def iter_rows(
        self,
        min_row: Optional[int] = None,
        max_row: Optional[int] = None,
        min_col: Optional[int] = None,
        max_col: Optional[int] = None,
        values_only: bool = False,
    ) -> Generator[tuple[Any, ...]]: ...
    def iter_cols(
        self,
        min_col: Optional[int] = None,
        max_col: Optional[int] = None,
        min_row: Optional[int] = None,
        max_row: Optional[int] = None,
        values_only: bool = False,
    ) -> Generator[tuple[Any, ...]]: ...
    @property
    def values(self) -> Generator[tuple[Any, ...]]: ...
    def cell(self, row: int, column: int, value: Any = None) -> Cell: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    @overload
    def __getitem__(self, key: str) -> Cell: ...
    @overload
    def __getitem__(self, key: int) -> tuple[Cell, ...]: ...
    def append(self, iterable: Iterable[Any]) -> None: ...
    def append_rows(self, rows_data: Iterable[Iterable[Any]]) -> None: ...
    def merge_cells(self, range_string: str) -> None: ...
    def unmerge_cells(self, range_string: str) -> None: ...
    def insert_rows(self, idx: int, amount: int = 1) -> None: ...
    def delete_rows(self, idx: int, amount: int = 1) -> None: ...
    def insert_cols(self, idx: int, amount: int = 1) -> None: ...
    def delete_cols(self, idx: int, amount: int = 1) -> None: ...
    def add_image(self, img: Any, anchor: Optional[str] = None) -> None: ...
    def add_data_validation(self, dv: Any) -> None: ...
