import os
from collections.abc import Iterator
from typing import Any

from openpyxl_rust.properties import DocumentProperties
from openpyxl_rust.worksheet import Worksheet

class DefinedName:
    name: str
    attr_text: str | None
    def __init__(self, name: str, attr_text: str | None = None) -> None: ...

class _DefinedNames:
    def __init__(self, workbook: Workbook) -> None: ...
    def add(self, defined_name: DefinedName) -> None: ...
    def __getitem__(self, name: str) -> DefinedName: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[DefinedName]: ...

class Workbook:
    defined_names: _DefinedNames
    properties: DocumentProperties
    def __init__(self) -> None: ...
    @property
    def active(self) -> Worksheet | None: ...
    @active.setter
    def active(self, value: Worksheet | int) -> None: ...
    def create_sheet(self, title: str | None = None) -> Worksheet: ...
    def remove(self, worksheet: Worksheet) -> None: ...
    @property
    def sheetnames(self) -> list[str]: ...
    def __getitem__(self, name: str) -> Worksheet: ...
    def __iter__(self) -> Iterator[Worksheet]: ...
    def __len__(self) -> int: ...
    def save(self, filename: str | bytes | os.PathLike | Any) -> None: ...
