from collections.abc import Generator, Iterable
from typing import Any, overload

from openpyxl_rust.cell import Cell
from openpyxl_rust.header_footer import HeaderFooter
from openpyxl_rust.page import PageMargins, PrintOptions, PrintPageSetup
from openpyxl_rust.page_break import BreakList
from openpyxl_rust.protection import SheetProtection

class ColumnDimension:
    width: float | None
    hidden: bool
    outline_level: int
    bestFit: bool
    def __init__(self) -> None: ...

class RowDimension:
    height: float | None
    hidden: bool
    outline_level: int
    def __init__(self) -> None: ...

class _ColumnDimensionsDict:
    def __init__(self) -> None: ...
    def __getitem__(self, key: str) -> ColumnDimension: ...
    def items(self) -> Iterable[tuple[str, ColumnDimension]]: ...

class _RowDimensionsDict:
    def __init__(self) -> None: ...
    def __getitem__(self, key: int) -> RowDimension: ...
    def items(self) -> Iterable[tuple[int, RowDimension]]: ...

class _AutoFilter:
    def __init__(self) -> None: ...
    @property
    def ref(self) -> str | None: ...
    @ref.setter
    def ref(self, value: str | None) -> None: ...
    def add_filter_column(self, col_id: int, vals: Iterable[str], blank: bool = False) -> None: ...

class _ConditionalFormattingList:
    def __init__(self) -> None: ...
    def add(self, range_string: str, rule: Any) -> None: ...

class Worksheet:
    ORIENTATION_PORTRAIT: str
    ORIENTATION_LANDSCAPE: str
    PAPERSIZE_LETTER: int
    PAPERSIZE_LEGAL: int
    PAPERSIZE_A4: int
    PAPERSIZE_A5: int

    column_dimensions: _ColumnDimensionsDict
    row_dimensions: _RowDimensionsDict
    freeze_panes: str | None
    merged_cell_ranges: list[tuple[str, str]]
    auto_filter: _AutoFilter
    protection: SheetProtection
    page_setup: PrintPageSetup
    page_margins: PageMargins
    print_options: PrintOptions
    print_area: str | None
    print_title_rows: str | None
    print_title_cols: str | None
    conditional_formatting: _ConditionalFormattingList
    row_breaks: BreakList
    col_breaks: BreakList
    oddHeader: HeaderFooter
    oddFooter: HeaderFooter

    def __init__(
        self,
        title: str = "Sheet",
        workbook: Any | None = None,
        sheet_idx: int | None = None,
    ) -> None: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def sheet_state(self) -> str: ...
    @sheet_state.setter
    def sheet_state(self, value: str) -> None: ...
    @property
    def zoom(self) -> int | None: ...
    @zoom.setter
    def zoom(self, value: int | None) -> None: ...
    def auto_fit_columns(self) -> None: ...
    @property
    def min_row(self) -> int | None: ...
    @property
    def max_row(self) -> int | None: ...
    @property
    def min_column(self) -> int | None: ...
    @property
    def max_column(self) -> int | None: ...
    @property
    def dimensions(self) -> str: ...
    def iter_rows(
        self,
        min_row: int | None = None,
        max_row: int | None = None,
        min_col: int | None = None,
        max_col: int | None = None,
        values_only: bool = False,
    ) -> Generator[tuple[Any, ...]]: ...
    def iter_cols(
        self,
        min_col: int | None = None,
        max_col: int | None = None,
        min_row: int | None = None,
        max_row: int | None = None,
        values_only: bool = False,
    ) -> Generator[tuple[Any, ...]]: ...
    @property
    def values(self) -> Generator[tuple[Any, ...]]: ...
    def cell(self, row: int, column: int, value: Any = None) -> Cell: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    @overload
    def __getitem__(self, key: str) -> Cell: ...
    @overload
    def __getitem__(self, key: int) -> tuple[Cell, ...]: ...
    def append(self, iterable: Iterable[Any]) -> None: ...
    def append_rows(self, rows_data: Iterable[Iterable[Any]]) -> None: ...
    def merge_cells(self, range_string: str) -> None: ...
    def unmerge_cells(self, range_string: str) -> None: ...
    def insert_rows(self, idx: int, amount: int = 1) -> None: ...
    def delete_rows(self, idx: int, amount: int = 1) -> None: ...
    def insert_cols(self, idx: int, amount: int = 1) -> None: ...
    def delete_cols(self, idx: int, amount: int = 1) -> None: ...
    def add_image(self, img: Any, anchor: str | None = None) -> None: ...
    def add_data_validation(self, dv: Any) -> None: ...
    def add_table(self, table: Any) -> None: ...
    def add_chart(self, chart: Any, anchor: str | None = None) -> None: ...
