import os
from collections.abc import Iterator
from typing import Any, Optional, Union

from openpyxl_rust.worksheet import Worksheet

class DefinedName:
    name: str
    attr_text: Optional[str]
    def __init__(self, name: str, attr_text: Optional[str] = None) -> None: ...

class _DefinedNames:
    def __init__(self, workbook: Workbook) -> None: ...
    def add(self, defined_name: DefinedName) -> None: ...
    def __getitem__(self, name: str) -> DefinedName: ...
    def __contains__(self, name: str) -> bool: ...
    def __iter__(self) -> Iterator[DefinedName]: ...

class Workbook:
    defined_names: _DefinedNames
    def __init__(self) -> None: ...
    @property
    def active(self) -> Optional[Worksheet]: ...
    @active.setter
    def active(self, value: Union[Worksheet, int]) -> None: ...
    def create_sheet(self, title: Optional[str] = None) -> Worksheet: ...
    def remove(self, worksheet: Worksheet) -> None: ...
    @property
    def sheetnames(self) -> list[str]: ...
    def __getitem__(self, name: str) -> Worksheet: ...
    def __iter__(self) -> Iterator[Worksheet]: ...
    def __len__(self) -> int: ...
    def save(self, filename: Union[str, bytes, os.PathLike, Any]) -> None: ...
