class PatternFill:
    fill_type: str | None
    start_color: str | None
    end_color: str | None
    def __init__(
        self,
        fill_type: str | None = None,
        start_color: str | None = None,
        end_color: str | None = None,
        fgColor: str | None = None,
        bgColor: str | None = None,
    ) -> None: ...
    @property
    def fgColor(self) -> str | None: ...
    @fgColor.setter
    def fgColor(self, value: str | None) -> None: ...
    @property
    def bgColor(self) -> str | None: ...
    @bgColor.setter
    def bgColor(self, value: str | None) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
